version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: picgo_db
      POSTGRES_USER: picgo_user
      POSTGRES_PASSWORD: picgo_pass
#    ports:
#      - "5434:5434"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: picgo_app
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/picgo_db
      SPRING_DATASOURCE_USERNAME: picgo_user
      SPRING_DATASOURCE_PASSWORD: picgo_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    depends_on:
      - db

volumes:
  db_data:
